// All build data lives here so the markup stays clean.
// Prices are USD ballpark, current-ish — friend should still spot-check before buying.

export const PARTS = [
  {
    id: "cpu",
    role: "Processor",
    name: "AMD Ryzen 5 5600",
    img: "images/cpu.jpg",
    price: 110,
    blurb:
      "Six Zen-3 cores at 3.5/4.4 GHz. Pairs perfectly with a 3070 — no bottleneck at 1440p, runs cool, and AM4 boards stay cheap.",
    specs: ["6c / 12t", "65 W TDP", "Socket AM4", "Includes Wraith Stealth"],
    link: "https://www.amd.com/en/products/cpu/amd-ryzen-5-5600",
  },
  {
    id: "motherboard",
    role: "Motherboard",
    name: "ASRock B550M-ITX/ac",
    img: "images/motherboard.jpg",
    price: 140,
    blurb:
      "Mini-ITX B550 with PCIe 4.0, Wi-Fi 6 add-in, 2.5Gb LAN, and a workable VRM for the 5600. Boring is the right answer here.",
    specs: ["Mini-ITX", "B550", "PCIe 4.0 x16", "Wi-Fi + 2.5GbE"],
    link: "https://www.asrock.com/mb/AMD/B550M-ITXac/",
  },
  {
    id: "ram",
    role: "Memory",
    name: "Corsair Vengeance LPX 32 GB DDR4-3200",
    img: "images/ram.jpg",
    price: 75,
    blurb:
      "Two 16 GB sticks at 3200 MHz CL16 — the AM4 sweet spot. Low-profile heatsinks clear any cooler.",
    specs: ["2 × 16 GB", "DDR4-3200", "CL16", "1.35 V"],
    link: "https://www.corsair.com/us/en/p/memory/cmk32gx4m2e3200c16/vengeance-lpx-32gb-2-x-16gb-ddr4-dram-3200mhz-c16-memory-kit-black-cmk32gx4m2e3200c16",
  },
  {
    id: "ssd",
    role: "Storage",
    name: "WD Blue SN570 1 TB NVMe",
    img: "images/ssd.jpg",
    price: 60,
    blurb:
      "PCIe 3.0, 3500/3000 MB/s, 5-year warranty. Cheap, reliable, no DRAM-cache complaints in real-world use.",
    specs: ["1 TB", "M.2 2280", "PCIe 3.0 ×4", "3500 MB/s read"],
    link: "https://www.westerndigital.com/products/internal-drives/wd-blue-sn570-nvme-ssd",
  },
  {
    id: "psu",
    role: "Power Supply",
    name: "FSP Dagger Pro 650 W SFX",
    img: "images/psu.jpg",
    price: 120,
    blurb:
      "80+ Gold, fully modular, 650 W is plenty for a 5600 + 3070. SFX form factor keeps every case option open.",
    specs: ["650 W", "SFX", "80+ Gold", "Fully modular"],
    link: "https://www.fsplifestyle.com/us/product/DAGGERPRO650W.html",
  },
  {
    id: "cooler",
    role: "CPU Cooler (default)",
    name: "Thermalright Peerless Assassin 120 SE",
    img: "images/cooler.jpg",
    price: 40,
    height: 155,
    blurb:
      "The legendary $40 dual-tower. Cools the 5600 silently — if it fits. 155 mm tall, so most SFF cases need a smaller air cooler or a 240 mm AIO instead. Compatibility shown per case below.",
    specs: ["155 mm tall", "Dual tower / 6 heatpipes", "2 × 120 mm fans", "Air"],
    link: "https://www.thermalright.com/product/peerless-assassin-120-se/",
  },
];

// Cooler clearance & compatibility data is the trickiest part of SFF — surface it.
// Numbers from manufacturer spec sheets.
export const CASES = [
  {
    id: "nr200p",
    name: "Cooler Master NR200P V3",
    img: "images/case.png",
    buildImg: "images/build-nr200p.png",
    price: 150,
    volume: 18.25,
    gpuMax: 356,
    coolerMax: 153,
    radMax: "280 mm top",
    psu: "SFX / SFX-L",
    materials: "Aluminum + steel + mesh",
    vibe: "The classic upgrade pick — refined, airy, easy to build in.",
    fitsPA120: false, // 155 > 153
    note: "PA120 SE is 155 mm — 2 mm too tall. Plan a 240/280 mm AIO or swap to a 150 mm-class cooler.",
    color: "#7aa2ff",
  },
  {
    id: "a4h2o",
    name: "Lian Li A4-H2O",
    img: "images/case-a4h2o.jpg",
    buildImg: "images/build-a4h2o.png",
    price: 130,
    volume: 11,
    gpuMax: 322,
    coolerMax: 67,
    radMax: "240 mm side",
    psu: "SFX / SFX-L",
    materials: "Aluminum sandwich",
    vibe: "Tiniest sleeve-of-saltines layout. Sandwich style with a 240 AIO front-and-center.",
    fitsPA120: false,
    note: "AIO required — 67 mm clearance only. Plan on the 240 mm rad in the side panel.",
    color: "#ff7eb6",
  },
  {
    id: "terra",
    name: "Fractal Design Terra",
    img: "images/case-terra.jpg",
    buildImg: "images/build-terra.png",
    price: 180,
    volume: 10.4,
    gpuMax: 322,
    coolerMax: 77,
    radMax: "Single-fan front",
    psu: "SFX / SFX-L",
    materials: "Anodized aluminum + walnut",
    vibe: "Furniture-grade. The walnut spine reads 'small studio Mac mini'.",
    fitsPA120: false,
    note: "77 mm cooler clearance — low-profile air or 120/140 AIO only.",
    color: "#c0a172",
  },
  {
    id: "revolt3",
    name: "Hyte Revolt 3",
    img: "images/case-revolt3.jpg",
    buildImg: "images/build-revolt3.png",
    price: 130,
    volume: 18.4,
    gpuMax: 335,
    coolerMax: 140,
    radMax: "AIO not supported (air only)",
    psu: "SFX (700 W bundled)",
    materials: "Steel + plastic + handle",
    vibe: "LAN-party briefcase. Built-in handle, comes with a 700 W PSU + cables.",
    fitsPA120: false,
    note: "140 mm clearance — Noctua NH-D9L / NH-L12 Sx77 / be quiet! Shadow Rock LP fit. PA120 SE doesn't.",
    color: "#ff5d3a",
  },
  {
    id: "tr100",
    name: "Thermaltake TR100",
    img: "images/case-tr100.jpg",
    buildImg: "images/build-tr100.png",
    price: 100,
    volume: 18.4,
    gpuMax: 360,
    coolerMax: 70,
    radMax: "280 mm top",
    psu: "SFX",
    materials: "Steel mesh, color options",
    vibe: "Cheapest SFF that doesn't look cheap — Snow / Matcha / Blue colorways.",
    fitsPA120: false,
    note: "70 mm air only — go AIO if you want sub-75 °C under sustained load.",
    color: "#5dd5b2",
  },
  {
    id: "t9",
    name: "Jonsbo T9",
    img: "images/case-t9.jpg",
    buildImg: "images/build-t9.png",
    price: 200,
    volume: 11.3,
    gpuMax: 310,
    coolerMax: 75,
    radMax: "240 mm side",
    psu: "SFX up to 100 mm",
    materials: "Aluminum + walnut base",
    vibe: "A4-style cube with wood. Minimalist, conversation piece on a desk.",
    fitsPA120: false,
    note: "75 mm clearance — AIO recommended for the 5600.",
    color: "#a78bfa",
  },
];

// Compatibility & "what to actually buy for the cooler" given the chosen case
export const COOLER_ALTERNATIVES = {
  air_lowprofile: {
    name: "Noctua NH-L12 Sx77 (low-profile air)",
    height: 77,
    price: 75,
    ok: ["a4h2o", "terra", "revolt3", "tr100", "t9", "nr200p"],
  },
  aio_240: {
    name: "240 mm AIO (e.g. Arctic Liquid Freezer III 240)",
    height: 27,
    price: 90,
    ok: ["nr200p", "a4h2o", "tr100", "t9"],
  },
  air_full: {
    name: "Thermalright Peerless Assassin 120 SE",
    height: 155,
    price: 40,
    ok: [], // none of the SFF cases listed fit it cleanly
  },
};
