// Build data. Each part has a default + alternatives the user can swap to.
// Cases include cooler clearance so the picker can warn about fit.
// Prices USD ballpark — spot check before buying.

export const PARTS = [
  {
    id: "cpu",
    role: "CPU",
    options: [
      { name: "AMD Ryzen 5 5600", price: 110, specs: "6c/12t · 65W · AM4 · stock cooler incl.", link: "https://www.amd.com/en/products/cpu/amd-ryzen-5-5600", note: "Sweet spot for a 3070. Zero bottleneck at 1440p." },
      { name: "AMD Ryzen 5 5600X", price: 140, specs: "6c/12t · 65W · AM4 · ~5–8% faster than 5600", link: "https://www.amd.com/en/products/cpu/amd-ryzen-5-5600x" },
      { name: "AMD Ryzen 7 5700X", price: 170, specs: "8c/16t · 65W · AM4 · multi-thread upgrade", link: "https://www.amd.com/en/products/cpu/amd-ryzen-7-5700x" },
      { name: "AMD Ryzen 7 5800X3D", price: 280, specs: "8c/16t · 105W · AM4 · 96MB 3D V-Cache, fastest gaming on AM4", link: "https://www.amd.com/en/products/cpu/amd-ryzen-7-5800x3d", note: "Overkill for a 3070, but ages well if Luccas upgrades the GPU later." },
    ],
  },
  {
    id: "motherboard",
    role: "Motherboard",
    options: [
      { name: "ASRock B550M-ITX/ac", price: 140, specs: "Mini-ITX · B550 · PCIe 4.0 · WiFi 6 · 2.5GbE", link: "https://www.asrock.com/mb/AMD/B550M-ITXac/", note: "Boring-correct. Good VRM for a 5600/5700X." },
      { name: "Gigabyte B550I Aorus Pro AX", price: 180, specs: "Mini-ITX · B550 · PCIe 4.0 · WiFi 6 · 2.5GbE · stronger VRM", link: "https://www.gigabyte.com/Motherboard/B550I-AORUS-PRO-AX-rev-10" },
      { name: "MSI B550I Gaming Edge WiFi", price: 190, specs: "Mini-ITX · B550 · PCIe 4.0 · WiFi 6 · 2.5GbE", link: "https://www.msi.com/Motherboard/MPG-B550I-GAMING-EDGE-WIFI" },
      { name: "ASUS ROG Strix B550-I Gaming", price: 230, specs: "Mini-ITX · B550 · PCIe 4.0 · WiFi 6 · 2.5GbE · best VRM in class", link: "https://rog.asus.com/motherboards/rog-strix/rog-strix-b550-i-gaming-model/" },
    ],
  },
  {
    id: "ram",
    role: "Memory",
    options: [
      { name: "Corsair Vengeance LPX 32GB DDR4-3200 CL16", price: 75, specs: "2 × 16GB · low profile · clears any cooler", link: "https://www.corsair.com/us/en/p/memory/cmk32gx4m2e3200c16/vengeance-lpx-32gb-2-x-16gb-ddr4-dram-3200mhz-c16-memory-kit-black-cmk32gx4m2e3200c16" },
      { name: "G.Skill Ripjaws V 32GB DDR4-3600 CL16", price: 85, specs: "2 × 16GB · 3600 MHz is the AM4 sweet spot", link: "https://www.gskill.com/product/165/326/1562838665/F4-3600C16D-32GVKC" },
      { name: "Crucial Ballistix 32GB DDR4-3200 CL16", price: 75, specs: "2 × 16GB · Micron E-die, OCs well", link: "https://www.crucial.com/memory/ddr4/bl2k16g32c16u4b" },
      { name: "TeamGroup T-Force Vulcan Z 16GB DDR4-3200", price: 35, specs: "2 × 8GB · cheap path if budget is tight", link: "https://www.teamgroupinc.com/en/product/vulcan-z-ddr4" },
    ],
  },
  {
    id: "ssd",
    role: "Storage",
    options: [
      { name: "WD Blue SN570 1TB NVMe", price: 60, specs: "PCIe 3.0 · 3500/3000 MB/s · 5yr warranty", link: "https://www.westerndigital.com/products/internal-drives/wd-blue-sn570-nvme-ssd" },
      { name: "Samsung 980 1TB NVMe", price: 75, specs: "PCIe 3.0 · 3500/3000 MB/s · Samsung Magician", link: "https://www.samsung.com/us/computing/memory-storage/solid-state-drives/980-pcie-3-0-nvme-ssd-1tb-mz-v8v1t0b-am/" },
      { name: "Crucial P3 Plus 1TB NVMe", price: 65, specs: "PCIe 4.0 · 5000/3600 MB/s", link: "https://www.crucial.com/ssd/p3-plus/ct1000p3pssd8" },
      { name: "Samsung 990 EVO 2TB NVMe", price: 150, specs: "PCIe 4.0 · 2TB · room to grow", link: "https://www.samsung.com/us/computing/memory-storage/solid-state-drives/990-evo-pcie-4-0-nvme-ssd-2tb-mz-v9e2t0b-am/" },
    ],
  },
  {
    id: "psu",
    role: "Power Supply",
    options: [
      { name: "FSP Dagger Pro 650W SFX", price: 120, specs: "SFX · 80+ Gold · fully modular · plenty for 5600+3070", link: "https://www.fsplifestyle.com/us/product/DAGGERPRO650W.html" },
      { name: "Cooler Master V750 SFX Gold", price: 150, specs: "SFX · 80+ Gold · 750W · headroom for GPU upgrade", link: "https://www.coolermaster.com/catalog/power-supplies/v-series/v750-sfx-gold/" },
      { name: "Corsair SF750", price: 170, specs: "SFX · 80+ Platinum · the gold-standard SFX PSU", link: "https://www.corsair.com/us/en/p/psu/cp-9020186-na/sf-series-sf750-750-watt-80-plus-platinum-certified-fully-modular-sfx-power-supply-cp-9020186-na" },
      { name: "Corsair SF600", price: 130, specs: "SFX · 80+ Platinum · 600W is enough for 5600+3070", link: "https://www.corsair.com/us/en/p/psu/cp-9020182-na/sf-series-sf600-600-watt-80-plus-platinum-certified-fully-modular-sfx-power-supply-cp-9020182-na" },
    ],
  },
  {
    id: "cooler",
    role: "CPU Cooler",
    // The cooler is the trickiest — height drives case compatibility.
    // Each option has a height (mm) used by the case fit warning.
    options: [
      { name: "Thermalright Peerless Assassin 120 SE", price: 40, height: 155, specs: "155 mm · dual tower · best $/perf air cooler", link: "https://www.thermalright.com/product/peerless-assassin-120-se/", note: "Only fits in larger SFF cases (≥155 mm clearance)." },
      { name: "Noctua NH-L12 Sx77", price: 75, height: 77, specs: "77 mm · low profile · proven SFF cooler", link: "https://noctua.at/en/nh-l12-sx77" },
      { name: "Noctua NH-L9a-AM4 chromax", price: 55, height: 37, specs: "37 mm · ultra low profile · for the smallest cases", link: "https://noctua.at/en/nh-l9a-am4-chromax-black" },
      { name: "be quiet! Shadow Rock LP", price: 55, height: 75, specs: "75 mm · low profile · quiet", link: "https://www.bequiet.com/en/cpucooler/1351" },
      { name: "Thermalright AXP90-X53", price: 30, height: 53, specs: "53 mm · cheap & low profile · solid for 65W chips", link: "https://www.thermalright.com/product/axp90-x53/" },
      { name: "Arctic Liquid Freezer III 240 (AIO)", price: 90, height: 27, specs: "240 mm AIO · best-in-class cooling, needs rad space", link: "https://www.arctic.de/en/Liquid-Freezer-III-240/ACFRE00136A", note: "Needs a 240 mm radiator mount — check case rad support." },
    ],
  },
];

export const CASES = [
  {
    id: "nr200p",
    name: "Cooler Master NR200P V3",
    img: "images/case.png",
    price: 150,
    volume: 18.25,
    gpuMax: 356,
    coolerMax: 153,
    radMax: "280 mm top",
    psu: "SFX / SFX-L",
    materials: "Steel + mesh, side panel options",
    vibe: "Classic SFF pick. Easy first build, great airflow.",
    link: "https://www.coolermaster.com/en-global/products/masterbox-nr200p-v3/",
  },
  {
    id: "a4h2o",
    name: "Lian Li A4-H2O",
    img: "images/case-a4h2o.jpg",
    price: 130,
    volume: 11,
    gpuMax: 322,
    coolerMax: 67,
    radMax: "240 mm side (AIO required)",
    psu: "SFX / SFX-L",
    materials: "Aluminum sandwich",
    vibe: "Tiny sandwich layout. AIO mandatory.",
    link: "https://lian-li.com/product/a4-h2o/",
  },
  {
    id: "terra",
    name: "Fractal Design Terra",
    img: "images/case-terra.jpg",
    price: 180,
    volume: 10.4,
    gpuMax: 322,
    coolerMax: 77,
    radMax: "Single-fan front",
    psu: "SFX / SFX-L",
    materials: "Anodized aluminum + walnut",
    vibe: "Furniture-grade. Looks like a Mac mini.",
    link: "https://www.fractal-design.com/products/cases/terra/",
  },
  {
    id: "revolt3",
    name: "Hyte Revolt 3",
    img: "images/case-revolt3.jpg",
    price: 130,
    volume: 18.4,
    gpuMax: 335,
    coolerMax: 140,
    radMax: "Air only",
    psu: "SFX (700W incl.)",
    materials: "Steel + plastic + carry handle",
    vibe: "LAN-party briefcase. PSU + cables included.",
    link: "https://hyte.com/store/revolt-3",
  },
  {
    id: "tr100",
    name: "Thermaltake TR100",
    img: "images/case-tr100.jpg",
    price: 100,
    volume: 18.4,
    gpuMax: 360,
    coolerMax: 70,
    radMax: "280 mm top",
    psu: "SFX",
    materials: "Steel mesh, color options",
    vibe: "Cheapest decent SFF. Snow / Matcha / Blue.",
    link: "https://www.thermaltake.com/tr100-snow-mini-chassis.html",
  },
  {
    id: "t9",
    name: "Jonsbo T9",
    img: "images/case-t9.jpg",
    price: 200,
    volume: 11.3,
    gpuMax: 310,
    coolerMax: 75,
    radMax: "240 mm side",
    psu: "SFX (≤100mm)",
    materials: "Aluminum + walnut base",
    vibe: "A4-style cube with wood. Showpiece.",
    link: "https://www.jonsbo.com/en/products/T9.html",
  },
  // --- additions ---
  {
    id: "meshlicious",
    name: "SSUPD Meshlicious",
    img: "images/case.png",
    price: 150,
    volume: 14.6,
    gpuMax: 336,
    coolerMax: 73,
    radMax: "280 mm side",
    psu: "SFX / SFX-L (ATX w/ riser)",
    materials: "Steel mesh, modular panels",
    vibe: "All-mesh, infinitely flexible layout.",
  },
  {
    id: "q58",
    name: "Lian Li Q58",
    img: "images/case-q58.jpg",
    price: 170,
    volume: 14.3,
    gpuMax: 320,
    coolerMax: 73,
    radMax: "280 mm side",
    psu: "SFX / SFX-L",
    materials: "Mesh + tempered glass options",
    vibe: "Sandwich layout with PCIe 4.0 riser included.",
  },
  {
    id: "nr200p_og",
    name: "Cooler Master NR200P (original)",
    img: "images/case.png",
    price: 100,
    volume: 18.25,
    gpuMax: 330,
    coolerMax: 155,
    radMax: "280 mm top",
    psu: "SFX / SFX-L",
    materials: "Steel + tempered glass / vented",
    vibe: "Cheaper alt to V3. Same dimensions, slightly less polish.",
  },
  {
    id: "evolv_shift_xt",
    name: "Phanteks Evolv Shift XT",
    img: "images/case-evolv-shift-xt.webp",
    price: 170,
    volume: 18.5,
    gpuMax: 335,
    coolerMax: 89,
    radMax: "240 mm",
    psu: "SFX",
    materials: "Anodized aluminum, vertical tower form",
    vibe: "Tall tower SFF. Stands like a small speaker.",
  },
];
